version: '3'
services:
  results:
    image: cristiandavidgm/results:latest
    ports:
      - 8880:8880
    environment:
      - discovery.type=single-node
  results1:
      image: cristiandavidgm/results:latest
      depends_on:
        - results
  results2:
      image: cristiandavidgm/results:latest
      depends_on:
        - results
  results3:
      image: cristiandavidgm/results:latest
      depends_on:
        - results
  haproxy:
      build: ./haproxy
      ports:
          - 8881:8881
      depends_on:
        - results1
        - results2
        - results3